/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [SUMMARY_USE].[REPORT_ID],
      [SUMMARY_USE].[REPORT_UNIT_ID],
      [SUMMARY_USE].[SUMMARY_SEQ],
      [SUMMARY_USE].[BENEFICIAL_USE_ID],
	  [VALUE],
      [SUMMARY_USE].[FRESH_SALINE_IND],
      [SUMMARY_USE].[SOURCE_TYPE],
      [SUMMARY_USE].[POWER_GENERATED],
      [SUMMARY_USE].[POPULATION_SERVED],
	   [S_USE_AMOUNT].[AMOUNT],
      [S_USE_AMOUNT].[CONSUMPTIVE_INDICATOR],
      [S_USE_AMOUNT].[METHOD_ID]

  FROM [WaDEwre].[wade].[SUMMARY_USE]

    JOIN [WaDEwre].[wade].[S_USE_AMOUNT]

  ON [S_USE_AMOUNT].[REPORT_ID] =[SUMMARY_USE].[REPORT_ID] AND
      [S_USE_AMOUNT].[REPORT_UNIT_ID]=[SUMMARY_USE].[REPORT_UNIT_ID] AND
      [S_USE_AMOUNT].[BENEFICIAL_USE_ID]=[SUMMARY_USE].[BENEFICIAL_USE_ID] AND
      [S_USE_AMOUNT].[SUMMARY_SEQ]= [SUMMARY_USE].[SUMMARY_SEQ]

	  LEFT JOIN 
	  [WaDEwre].[wade].[LU_BENEFICIAL_USE]
	  ON [SUMMARY_USE].[BENEFICIAL_USE_ID]=[LU_BENEFICIAL_USE].[LU_SEQ_NO]

	  WHERE [SUMMARY_USE].[BENEFICIAL_USE_ID]='89' 

	  --AND [SUMMARY_USE].[REPORT_UNIT_ID]='16010203'
